import { NextPage } from "next";
import Head from "next/head";

interface Props {
  children: React.ReactNode;
}

const Page: NextPage<Props> = ({ children }) => {
  return (
    <>
      <Head>
        <title>Hotel Booking</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>{children}</main>
    </>
  );
};
export default Page;
